name: Prepare test data

on:
    schedule:
        - cron: "0 0 1 * *" # run once a month to prevent artifact expiration
    workflow_dispatch:
    # Uncomment and adjust the branch name if you need to add new datasets to the artifact.
    # It needs to be a branch in the spatialdata-io origin repository, not from a fork.
    # push:
    #   branches:
    #     - main

jobs:
    prepare-data:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Download test datasets
              run: |
                  python scripts/download_test_data.py --output ./data

            - name: Upload artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: data
                  path: ./data
                  if-no-files-found: error
